### ISSUE TITLE
When Modal pops up background is getting dark 

### ISSUE THREAD

**Issue by C-Das** [jeffreyhshapiro/rutgers-virtual-flyer#4]
Needs to make sure the home page background remains

**Comment by jeffreyhshapiro** [comment]
@C-Das i made a temporary fix for the modal issue.  when clicking the login/register link in the navbar, it was linking to a separate route which is why the background was disappearing.  i put the code for the modals in the homeView.handlebars folder and in login.js put the $("#loginModal").modal("show") inside an on click callback so that way it will only display when clicked. i put the code inside a branch called modal-display-issue. i'll open a pull request, let me know what you think of it!

**Comment by C-Das** [comment]
This is great. I pulled and tested it. Works fine. We should merge this to master. Thanks, good fix

**Comment by jeffreyhshapiro** [comment]
i forgot to say before that the issue is that when you open the email modal from the sign in modal the screen resizes. we need to fix that part
